'use strict'
import 'raw-loader!./pug/index.pug'
import style from './assets/sass/style.sass'
import './js/gamePlay.js'
import './js/positionGenerator.js'
import './js/gameControls.js'
import './js/sound.js'