#!/bin/bash

eslint="pnpm eslint"
stylelint="pnpm stylelint"

if ! $eslint; then
    echo "Error, check eslinter"
    exit 1
fi

if ! $stylelint; then
    echo "Error, check stylelinter"
    exit 1
fi
